# Generated by Django 3.1.2 on 2020-10-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikl',
            fields=[
                ('barkod_artikla', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv_artikla', models.CharField(max_length=100)),
            ],
        ),
    ]
