# Generated by Django 3.1.2 on 2020-12-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('sif_kategorija', models.AutoField(primary_key=True, serialize=False)),
                ('naz_kategorija', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Potkategorija',
            fields=[
                ('sif_potkategorija', models.AutoField(primary_key=True, serialize=False)),
                ('naz_potkategorija', models.CharField(max_length=100)),
                ('kategorija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartCart.kategorija')),
            ],
        ),
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('sif_uloga', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('naz_uloga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vrsta',
            fields=[
                ('sif_vrsta', models.AutoField(primary_key=True, serialize=False)),
                ('naz_vrsta', models.CharField(max_length=100)),
                ('potkategorija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartCart.potkategorija')),
            ],
        ),
        migrations.CreateModel(
            name='PrivremenaLozinka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lozinka', models.CharField(max_length=100, null=True)),
                ('istice', models.CharField(max_length=100, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnemoguceniRacun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.CharField(max_length=100, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='secretcode',
            name='uloga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.uloga'),
        ),
        migrations.CreateModel(
            name='OpisArtikla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_artikla', models.CharField(max_length=100)),
                ('opis_artikla', models.CharField(max_length=5000, null=True)),
                ('broj_glasova', models.IntegerField(null=True)),
                ('masa', models.IntegerField(null=True)),
                ('barkod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.artikl')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trgovina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.trgovina')),
                ('vrsta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.vrsta')),
                ('zemlja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.zemlja_porijekla')),
            ],
            options={
                'unique_together': {('vrsta', 'zemlja', 'trgovina')},
            },
        ),
    ]
