# Generated by Django 3.1.2 on 2020-10-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trgovina',
            fields=[
                ('sifTrgovina', models.IntegerField(primary_key=True, serialize=False)),
                ('nazTrgovina', models.CharField(max_length=100)),
            ],
        ),
    ]
