# Generated by Django 3.1.2 on 2020-12-04 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onemoguceniracun',
            name='email',
        ),
        migrations.AddField(
            model_name='onemoguceniracun',
            name='emailAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
