# Generated by Django 3.1.2 on 2020-12-04 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0002_auto_20201204_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusermodel',
            name='onemogucio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
