# Generated by Django 3.1.2 on 2020-12-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0002_auto_20201203_1414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opisartikla',
            unique_together=set(),
        ),
    ]
