# Generated by Django 3.1.2 on 2020-12-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0003_baseusermodel_onemogucio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretcode',
            name='uloga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.uloga'),
        ),
    ]
