# Generated by Django 3.1.2 on 2020-10-31 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0003_trgovina_artikli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvođač',
            fields=[
                ('naziv', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zemlja_porijekla',
            fields=[
                ('naziv', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='artikl',
            name='autor_naziva',
            field=models.CharField(default='puro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='autor_opisa',
            field=models.CharField(default='puro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='autor_proizvođača',
            field=models.CharField(default='puro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='autor_zemlje_porijekla',
            field=models.CharField(default='puro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='opis_artikla',
            field=models.CharField(default='bla bla bal ablablabllbalb bal vblab bla', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='vegan',
            field=models.CharField(default='NO', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='vote_count_naziva',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='vote_count_opisa',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='vote_count_proizvođača',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='vote_count_zemlje_porijekla',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikl',
            name='proizvođač',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartCart.proizvođač'),
        ),
        migrations.AddField(
            model_name='artikl',
            name='zemlja_porijekla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartCart.zemlja_porijekla'),
        ),
    ]
