# Generated by Django 3.1.2 on 2020-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0003_auto_20201203_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloga',
            name='sif_uloga',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
