# Generated by Django 3.1.2 on 2020-12-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0004_auto_20201203_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potkategorija',
            old_name='kategorija',
            new_name='sif_kategorija',
        ),
    ]
