# Generated by Django 3.1.2 on 2020-11-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0004_auto_20201031_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikl',
            name='autor_naziva',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='autor_opisa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='autor_proizvođača',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='autor_zemlje_porijekla',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='opis_artikla',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='vegan',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='vote_count_opisa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='vote_count_proizvođača',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artikl',
            name='vote_count_zemlje_porijekla',
            field=models.IntegerField(null=True),
        ),
    ]
