# Generated by Django 3.1.2 on 2020-11-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0005_auto_20201101_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikl',
            name='vote_count_naziva',
            field=models.IntegerField(null=True),
        ),
    ]
