# Generated by Django 3.1.2 on 2020-12-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0005_auto_20201203_1709'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='potkategorija',
            constraint=models.UniqueConstraint(fields=('sif_kategorija', 'sif_potkategorija'), name='constraint_1'),
        ),
    ]
