# Generated by Django 3.1.2 on 2020-12-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0006_auto_20201203_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vrsta',
            old_name='potkategorija',
            new_name='sif_potkategorija',
        ),
        migrations.AddConstraint(
            model_name='vrsta',
            constraint=models.UniqueConstraint(fields=('sif_potkategorija', 'sif_vrsta'), name='constraint_2'),
        ),
    ]
