# Generated by Django 3.1.2 on 2020-12-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0008_auto_20201203_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusermodel',
            name='sif_uloga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.uloga'),
        ),
        migrations.AddField(
            model_name='opisartikla',
            name='id_trgovina_artikl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.trgovinaartikli'),
        ),
    ]
