# Generated by Django 3.1.2 on 2020-12-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0009_auto_20201204_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretcode',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='sif_uloga',
        ),
        migrations.RemoveField(
            model_name='secretcode',
            name='uloga',
        ),
    ]
