# Generated by Django 3.1.2 on 2020-12-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0009_auto_20201204_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trgovinaartikli',
            name='id',
        ),
        migrations.AddField(
            model_name='trgovinaartikli',
            name='id_trgovina_artikl',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
