# Generated by Django 3.1.2 on 2020-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0010_auto_20201204_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='uloga',
            name='auth_level',
            field=models.CharField(choices=[('G', 'Gost'), ('K', 'Kupac'), ('T', 'Trgovac'), ('A', 'Administrator')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
