# Generated by Django 3.1.2 on 2020-12-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0010_auto_20201204_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trgovinaartikli',
            name='id_trgovina_artikl',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
