# Generated by Django 3.1.2 on 2020-12-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0011_uloga_auth_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretcode',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='uloga',
            name='naz_uloga',
        ),
    ]
