# Generated by Django 3.1.2 on 2020-12-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0012_auto_20201204_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusermodel',
            name='uloga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartCart.uloga'),
        ),
    ]
