# Generated by Django 3.1.2 on 2020-12-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartCart', '0013_baseusermodel_uloga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretcode',
            options={'managed': True},
        ),
    ]
